doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            car_id: 'App\Model\Car\Entity\Car\CarIdType'
            brand_id: 'App\Model\Car\Entity\Brand\BrandIdType'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Car:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Car/Entity'
                prefix: 'App\Model\Car\Entity'
                alias: Car
