version: '3.5'
services:
  nginx:
    container_name: credit_tz_nginx
    volumes:
      - ./../:/var/www/site
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    image: nginx
    ports:
      - "8080:80"
    links:
      - fpm
    networks:
      - credit_tz_net
  fpm:
    container_name: credit_tz_fpm
    build:
      context: ./fpm
      args:
        - UID
        - USER_NAME
    user: ${USER_NAME}
    working_dir: /var/www/site
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./../:/var/www/site
      - ./fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - credit_tz_net
  mysql:
    container_name: credit_tz_mysql
    image: mariadb:10.4.12-bionic
    command: --default-authentication-plugin=mysql_native_password  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=creadit_tz
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
    networks:
      - credit_tz_net
  redis:
    image: redis:4.0.9
    container_name: credit_tz_redis
    ports:
      - 6379:6379
    volumes:
      - "./redis/volumes:/data"
    networks:
      - credit_tz_net
networks:
  credit_tz_net:
    name: credit_tz_network
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"